export default function(router){
	router.map({
		'/index':{
			component:function(resolve){
				require(["./components/Hello"],resolve)
			}
		},
		'/shouye':{
			component:function(resolve){
				require(["./components/shouye"],resolve)
			}
		},
		'/tuijian':{
			component:function(resolve){
				require(["./subpage/tuijian"],resolve)
			}
		},
		'/personal':{
			component:function(resolve){
				require(["./subpage/person"],resolve)
			}
		},
		'/my':{
			component:function(resolve){
				require(["./subpage/my"],resolve)
			}
		},
		'/dzprice':{
			component:function(resolve){
				require(["./subpage/dzprice"],resolve)
			}
		},
		'/details':{
			component:function(resolve){
				require(["./subpage/details"],resolve)
			}
		},
		'/area':{
			component:function(resolve){
				require(["./subpage/area"],resolve)
			}
		},
		'/search':{
			component:function(resolve){
				require(["./subpage/search"],resolve)
			}
		},
		'/oneday':{
			component:function(resolve){
				require(["./subpage/oneday"],resolve)
			}
		},
		'/dingdan':{
			component:function(resolve){
				require(["./subpage/dingdan"],resolve)
			},
			subRoutes:{
				'/dall':{
					component:function(resolve) {
						require(["./subpage/sub/dall"],resolve)
					}
				},
				'/dlend':{
					component:function(resolve) {
						require(["./subpage/sub/dlend"],resolve)
					}
				},
				'/dgive':{
					component:function(resolve) {
						require(["./subpage/sub/dgive"],resolve)
					}
				}
			}
		},
		'/bplace':{
			component:function(resolve){
				require(["./subpage/bplace"],resolve)
			},
			subRoutes:{
				'/alls':{
					component:function(resolve) {
						require(["./subpage/sub/all"],resolve)
					}
				},
				'/theme':{
					component:function(resolve) {
						require(["./subpage/sub/theme"],resolve)
					}
				},
			}
		}
	})
}